CREATE DATABASE TIP_STREAMING;

USE TIP_STREAMING;
CREATE TABLE MEDIA (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, Nombre CHAR(100), Ruta CHAR(200));

INSERT INTO MEDIA (Nombre, Ruta) VALUES ('..','..');